[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
satch = "4D3Lfi2YVgFiqRaiN8SyBxJkob5cnbxHUo86xUtgqNoH"

[programs.devnet]
satch = "4D3Lfi2YVgFiqRaiN8SyBxJkob5cnbxHUo86xUtgqNoH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://normals-solanad-6ba0.devnet.rpcpool.com/aeafc746-238d-4bea-af16-6b69e62a4eab"
wallet = "~/.config/solana/id.json"

[provider.normals]
url = "https://normals-solanad-6ba0.devnet.rpcpool.com/aeafc746-238d-4bea-af16-6b69e62a4eab"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
